// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"learn-golang/src/db"
	"learn-golang/src/graph"
	"learn-golang/src/repository"
	"learn-golang/src/usecase"
)

// Injectors from wire.go:

func InitializeResolver(ctx context.Context) (*graph.Resolver, func(), error) {
	config := db.NewConfig()
	queries, cleanup, err := db.NewQueries(ctx, config)
	if err != nil {
		return nil, nil, err
	}
	idGenerator := repository.NewUuidGenerator()
	timeGenerator := repository.NewTimeGenerator()
	userRepository := repository.NewUserRepository(queries, idGenerator, timeGenerator)
	userUseCase := usecase.NewUserUseCase(userRepository)
	resolver := graph.NewResolver(userUseCase)
	return resolver, func() {
		cleanup()
	}, nil
}
