services:
  db:
    image: postgres:16.3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d golang -U golang" ]
      interval: 1s
      timeout: 10s
      retries: 30
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local