services:
  db:
    image: postgres:16.3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d golang -U golang" ]
      interval: 1s
      timeout: 10s
      retries: 30
    environment:
      POSTGRES_DB: golang
      POSTGRES_USER: golang
      POSTGRES_PASSWORD: golang
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local