version: '3'

tasks:
  setup:
    cmds:
      - go install github.com/99designs/gqlgen@v0.17.49
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.26.0
      - go install github.com/google/wire/cmd/wire@v0.6.0
  fmt:
    cmds:
      - go fmt ./...
  test:
    cmds:
      - go test -v ./...
  gen:
    cmds:
      - go generate ./...
      - gqlgen generate
      - sqlc generate
      - task: fmt
  run:
    cmds:
      - go run ./cmd/app/main.go
  migrate:
    cmds:
      - go run ./cmd/migrate/main.go
  push:
    cmds:
      - docker build --platform linux/amd64 -t asia-northeast1-docker.pkg.dev/playground-430113/learn-golang/api .
      - docker push asia-northeast1-docker.pkg.dev/playground-430113/learn-golang/api
      - docker build --build-arg cmd=cmd/migrate/main.go --platform linux/amd64 -t asia-northeast1-docker.pkg.dev/playground-430113/learn-golang/migrate .
      - docker push asia-northeast1-docker.pkg.dev/playground-430113/learn-golang/migrate