// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Content   string
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
}
