// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type Post struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Content   *string   `json:"content,omitempty"`
	UserID    string    `json:"userId"`
	CreatedAt time.Time `json:"createdAt"`
}

type Query struct {
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}
